config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'weather#index'
  post '/', to: 'weather#index', as: 'check_weather'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather.rb
# frozen_string_literal: true

class Weather < ApplicationRecord
  include ActiveSupport::NumberHelper

  def temp_f
    k_to_f(data.dig('main', 'temp'))
  end

  def feels_like_f
    k_to_f(data.dig('main', 'feels_like'))
  end

  def high_temp_f
    k_to_f(data.dig('main', 'temp_max'))
  end

  def low_temp_f
    k_to_f(data.dig('main', 'temp_min'))
  end

  def humidity
    data.dig('main', 'humidity')
  end

  def description
    data['weather'][0]['description']
  end

  def icon_uri
    data['weather'][0]['icon_uri']
  end

  # private

  def k_to_f(temp)
    number_to_rounded((((temp.to_f - 273.15) * (9.0 / 5.0)) + 32.0), precision: 2)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

class WeatherController < ApplicationController
  def index
    @original_address = address_params['address']
    return if @original_address.blank?

    verifier = MainStreet::AddressVerifier.new(@original_address)
    if verifier.success? && verifier.result.postal_code.present?
      @weather, @cached = CheckWeather.check(verifier.result.postal_code)
      @verified_address = verifier.result.address
    else
      @error_message = verifier.failure_message.presence || 'Zip code not found'
    end
  end

  private

  def address_params
    params.permit(:address)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/weather_helper.rb
# frozen_string_literal: true

module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cassie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/index.html.erb
<h1>Check the weather</h1>
<div>
<%= form_with url: check_weather_path do |form| %>
  <%= form.label :address, 'Address:' %>
  <%= form.text_field :address %>
  <%= form.submit 'Submit' %>
<% end %>
</div>
<br/>
<% if @error_message.present? && @original_address.present? %>
  <div>
    Error: </br>
    <%= @error_message  %>
  </div>
  <br/>
<% end %>

<% unless @original_address.blank? %>
  <div>
    Original address: </br>
    <%= @original_address %>
  </div>
  <br/>
<% end %>

<% unless @verified_address.blank? %>
  <div>
    Verified address: </br>
    <%= @verified_address %>
    </div>
    <br/>
<% end %>

<% unless @weather.blank? %>
  <div>
    The following weather result is <%= @cached ? '' : 'not ' %>cached.<br/><br/>
    Last retrieved at: <%= @weather.updated_at %><br/>
  </div>
  <h3>Weather for zip code <%= @weather.zip %>:</h3>
  <div>
    Temperature: <%= @weather.temp_f %> F<br/>
    Feels like: <%= @weather.feels_like_f %> F<br/>
    High: <%= @weather.high_temp_f %> F<br/>
    Low: <%= @weather.low_temp_f %> F<br/>
    Humidity: <%= @weather.humidity %>%<br/>
    Description: <%= @weather.description %><br/>
    <%= image_tag(@weather.icon_uri) %><br/>
  </div>
<% end %>

<br/>
<br/>
<br/>
<div>
  Address verification performed by <%= link_to 'Nominatim', 'https://nominatim.org/' %>.<br/>
  Weather from <%= link_to 'OpenWeather', 'https://openweathermap.org/api' %>.<br/>
</div>